var sourcesIndex = JSON.parse('{\
"altair_runtime":["",[["weights",[],["frame_system.rs","mod.rs","pallet_anchors.rs","pallet_balances.rs","pallet_collator_allowlist.rs","pallet_collective.rs","pallet_crowdloan_claim.rs","pallet_crowdloan_reward.rs","pallet_democracy.rs","pallet_fees.rs","pallet_identity.rs","pallet_loans.rs","pallet_migration_manager.rs","pallet_multisig.rs","pallet_nft_sales.rs","pallet_permissions.rs","pallet_pool_system.rs","pallet_preimage.rs","pallet_proxy.rs","pallet_scheduler.rs","pallet_timestamp.rs","pallet_treasury.rs","pallet_uniques.rs","pallet_utility.rs","pallet_vesting.rs"]]],["constants.rs","lib.rs","xcm.rs"]],\
"centrifuge_chain":["",[["rpc",[],["anchors.rs","mod.rs","pools.rs"]]],["chain_spec.rs","cli.rs","command.rs","main.rs","service.rs"]],\
"centrifuge_runtime":["",[["weights",[],["frame_system.rs","mod.rs","pallet_anchors.rs","pallet_balances.rs","pallet_collator_allowlist.rs","pallet_collective.rs","pallet_crowdloan_claim.rs","pallet_crowdloan_reward.rs","pallet_democracy.rs","pallet_fees.rs","pallet_identity.rs","pallet_migration_manager.rs","pallet_multisig.rs","pallet_preimage.rs","pallet_proxy.rs","pallet_scheduler.rs","pallet_timestamp.rs","pallet_treasury.rs","pallet_utility.rs","pallet_vesting.rs"]]],["lib.rs","xcm.rs"]],\
"cfg_primitives":["",[],["impls.rs","lib.rs"]],\
"cfg_test_utils":["",[["mocks",[],["accountant.rs","authority_origin.rs","mod.rs","nav.rs","order_manager.rs","orml_asset_registry.rs"]]],["lib.rs"]],\
"cfg_traits":["",[],["lib.rs","ops.rs","rewards.rs"]],\
"cfg_types":["",[],["adjustments.rs","consts.rs","epoch.rs","fee_keys.rs","fixed_point.rs","ids.rs","investments.rs","lib.rs","orders.rs","permissions.rs","time.rs","tokens.rs","xcm.rs"]],\
"cfg_utils":["",[],["lib.rs"]],\
"development_runtime":["",[["weights",[],["frame_system.rs","mod.rs","pallet_balances.rs","pallet_collator_allowlist.rs","pallet_crowdloan_claim.rs","pallet_crowdloan_reward.rs","pallet_fees.rs","pallet_keystore.rs","pallet_loans.rs","pallet_migration_manager.rs","pallet_nft_sales.rs","pallet_permissions.rs","pallet_pool_registry.rs","pallet_pool_system.rs"]]],["lib.rs","xcm.rs"]],\
"pallet_anchors":["",[],["common.rs","lib.rs","weights.rs"]],\
"pallet_bridge":["",[],["lib.rs","traits.rs","weights.rs"]],\
"pallet_claims":["",[],["lib.rs","weights.rs"]],\
"pallet_collator_allowlist":["",[],["lib.rs","weights.rs"]],\
"pallet_connectors":["",[],["contract.rs","lib.rs","message.rs","routers.rs","weights.rs"]],\
"pallet_crowdloan_claim":["",[],["lib.rs","weights.rs"]],\
"pallet_crowdloan_reward":["",[],["lib.rs","weights.rs"]],\
"pallet_fees":["",[],["lib.rs","weights.rs"]],\
"pallet_interest_accrual":["",[],["lib.rs","weights.rs"]],\
"pallet_investments":["",[],["lib.rs","weights.rs"]],\
"pallet_keystore":["",[],["lib.rs","weights.rs"]],\
"pallet_liquidity_rewards":["",[],["lib.rs","weights.rs"]],\
"pallet_loans":["",[],["functions.rs","lib.rs","loan_type.rs","math.rs","types.rs","weights.rs"]],\
"pallet_migration_manager":["",[],["lib.rs","weights.rs"]],\
"pallet_nft":["",[],["lib.rs","traits.rs","types.rs","weights.rs"]],\
"pallet_nft_sales":["",[],["lib.rs","weights.rs"]],\
"pallet_permissions":["",[],["lib.rs","weights.rs"]],\
"pallet_pool_registry":["",[],["lib.rs","weights.rs"]],\
"pallet_pool_system":["",[],["impls.rs","lib.rs","pool_types.rs","solution.rs","tranches.rs","weights.rs"]],\
"pallet_restricted_tokens":["",[],["impl_currency.rs","impl_fungible.rs","impl_fungibles.rs","lib.rs","weights.rs"]],\
"pallet_rewards":["",[["mechanism",[],["base.rs","deferred.rs"]]],["lib.rs","mechanism.rs"]],\
"proofs":["",[],["lib.rs"]],\
"runtime_common":["",[["apis",[],["anchors.rs","mod.rs","pools.rs"]]],["lib.rs"]],\
"runtime_integration_tests":["",[],["lib.rs"]]\
}');
createSourceSidebar();
